// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDptWP8jPd9L8vZz8zbcMHeRS8hD9T_kkY',
    appId: '1:144994644138:web:75ee8f064e49b56a8ae0d3',
    messagingSenderId: '144994644138',
    projectId: 'virtual-fridge-fed65',
    authDomain: 'virtual-fridge-fed65.firebaseapp.com',
    databaseURL: 'https://virtual-fridge-fed65-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'virtual-fridge-fed65.appspot.com',
    measurementId: 'G-HLR9T938FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYCk5hER_4S_I_87CwMkfPqSbfKz5XJYg',
    appId: '1:144994644138:android:1d734d5a9995146d8ae0d3',
    messagingSenderId: '144994644138',
    projectId: 'virtual-fridge-fed65',
    databaseURL: 'https://virtual-fridge-fed65-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'virtual-fridge-fed65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDop5kmtTBaToQ9yMkncgkNbWbZoze7Bt0',
    appId: '1:144994644138:ios:f93722e4eb15307c8ae0d3',
    messagingSenderId: '144994644138',
    projectId: 'virtual-fridge-fed65',
    databaseURL: 'https://virtual-fridge-fed65-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'virtual-fridge-fed65.appspot.com',
    iosClientId: '144994644138-rt3q33eqcvd27q9tj0t8o1la0vhgid66.apps.googleusercontent.com',
    iosBundleId: 'com.example.frigiderVirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDop5kmtTBaToQ9yMkncgkNbWbZoze7Bt0',
    appId: '1:144994644138:ios:f93722e4eb15307c8ae0d3',
    messagingSenderId: '144994644138',
    projectId: 'virtual-fridge-fed65',
    databaseURL: 'https://virtual-fridge-fed65-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'virtual-fridge-fed65.appspot.com',
    iosClientId: '144994644138-rt3q33eqcvd27q9tj0t8o1la0vhgid66.apps.googleusercontent.com',
    iosBundleId: 'com.example.frigiderVirtual',
  );
}
